version: "3.7"

networks:
  default:
    driver: bridge
 
services:
  keycloak:
    hostname: keycloak
    container_name: keycloak
    image:  jboss/keycloak:11.0.2
    restart: always
    environment:
      KEYCLOAK_USER:   
      KEYCLOAK_PASSWORD: 
      PROXY_ADDRESS_FORWARDING: "true"

  tunnel:
    image: cloudflare/cloudflared:2020.10.0
    container_name: tunnel
    environment:
      TUNNEL_HOSTNAME: 
      TUNNEL_URL: http://keycloak:8080
      TUNNEL_ORIGIN_CERT: /.cloudflared/cert.pem
      TUNNEL_RETRIES: 10
    volumes:
      - "~/.cloudflared/cert.pem:/.cloudflared/cert.pem"
    restart: always
    command: ["tunnel"]
    depends_on: 
      - keycloak
